// Common CSS config
const commonCSS = {
  "h1, h2, h3, h4, h5, h6": {
    "font-family": "var(--font-plus-jakarta-sans)",
  },
  ".header-xl": {
    "font-size": "72px",
    "line-height": "90px",
    "letter-spacing": "-0.02em",
  },
  ".header-lg": {
    "font-size": "60px",
    "line-height": "72px",
    "letter-spacing": "-0.02em",
  },
  ".header-md": {
    "font-size": "36px",
    "line-height": "44px",
    "letter-spacing": "-0.02em",
  },
  ".header-sm": {
    "font-size": "30px",
    "line-height": "38px",
  },
  ".header-xs": {
    "font-size": "24px",
    "line-height": "32px",
  },
  ".paragraph-xl": {
    "font-size": "20px",
    "line-height": "30px",
  },
  ".paragraph-lg": {
    "font-size": "18px",
    "line-height": "28px",
  },
  ".paragraph-md": {
    "font-size": "16px",
    "line-height": "24px",
  },
  ".paragraph-sm": {
    "font-size": "14px",
    "line-height": "20px",
  },
  ".paragraph-xs": {
    "font-size": "12px",
    "line-height": "18px",
  },
  "@layer base": {
    "*": {
      "border-color": "var(--border)",
      "outline-color": "rgb(var(--ring) / 0.5)",
    },
    body: {
      "background-color": "var(--background)",
      color: "var(--foreground)",
      "letter-spacing": "0em",
    },
  },
};

// Common theme variables (from @theme inline in globals.css)
const commonThemeVars = {
  "--color-primary-50": "var(--primary-50)",
  "--color-primary-100": "var(--primary-100)",
  "--color-primary-200": "var(--primary-200)",
  "--color-primary-300": "var(--primary-300)",
  "--color-primary-400": "var(--primary-400)",
  "--color-primary-500": "var(--primary-500)",
  "--color-primary-600": "var(--primary-600)",
  "--color-primary-700": "var(--primary-700)",
  "--color-primary-800": "var(--primary-800)",
  "--color-primary-900": "var(--primary-900)",
  "--color-primary-950": "var(--primary-950)",
  "--color-gray-50": "var(--gray-50)",
  "--color-gray-100": "var(--gray-100)",
  "--color-gray-200": "var(--gray-200)",
  "--color-gray-300": "var(--gray-300)",
  "--color-gray-400": "var(--gray-400)",
  "--color-gray-500": "var(--gray-500)",
  "--color-gray-600": "var(--gray-600)",
  "--color-gray-700": "var(--gray-700)",
  "--color-gray-800": "var(--gray-800)",
  "--color-gray-900": "var(--gray-900)",
  "--color-gray-950": "var(--gray-950)",
  "--color-success-50": "var(--success-50)",
  "--color-success-100": "var(--success-100)",
  "--color-success-200": "var(--success-200)",
  "--color-success-300": "var(--success-300)",
  "--color-success-400": "var(--success-400)",
  "--color-success-500": "var(--success-500)",
  "--color-warning-50": "var(--warning-50)",
  "--color-warning-100": "var(--warning-100)",
  "--color-warning-200": "var(--warning-200)",
  "--color-warning-300": "var(--warning-300)",
  "--color-warning-400": "var(--warning-400)",
  "--color-warning-500": "var(--warning-500)",
  "--color-error-50": "var(--error-50)",
  "--color-error-100": "var(--error-100)",
  "--color-error-200": "var(--error-200)",
  "--color-error-300": "var(--error-300)",
  "--color-error-400": "var(--error-400)",
  "--color-error-500": "var(--error-500)",
  "--color-info-50": "var(--info-50)",
  "--color-info-100": "var(--info-100)",
  "--color-info-200": "var(--info-200)",
  "--color-info-300": "var(--info-300)",
  "--color-info-400": "var(--info-400)",
  "--color-info-500": "var(--info-500)",

  // Accent Colors
  "--color-electric-cyan": "#00ffff",
  "--color-mint-green": "#80e786",
  "--color-teal-green": "#6be6bc",
  "--color-teal": "#6cafab",
  "--color-golden-sun": "#ffb800",
  "--color-sunset-orange": "#fd5c1d",
  "--color-rose-pink": "#f495a8",
  "--color-indigo-blue": "#435eec",
  "--color-amber-mustard": "#d08f18",
  "--color-sky-blue": "#46a7dd",
  "--color-soft-blue": "#8db4fc",

  // Tertiary Colors
  "--color-aqua": "#a0e7e5",
  "--color-peach": "#ffcba4",
  "--color-lavender": "#e6e6fa",
  "--color-coral": "#f08080",
  "--color-eggsh": "#f5f5dc",
  "--color-gray": "#d3d3d3",
  "--color-ice-blue": "#b4ceff",
  "--color-navy": "#49668a",

  // Shadcn Variables
  "--color-background": "var(--background)",
  "--color-foreground": "var(--primary-950)",
  "--color-primary": "var(--primary-500)",
  "--color-primary-foreground": "var(--primary-50)",
  "--color-secondary": "var(--primary-600)",
  "--color-secondary-foreground": "var(--primary-50)",
  "--color-sidebar-ring": "var(--primary-300)",
  "--color-sidebar-border": "var(--primary-200)",
  "--color-sidebar-accent-foreground": "var(--primary-50)",
  "--color-sidebar-accent": "var(--primary-600)",
  "--color-sidebar-primary-foreground": "var(--primary-50)",
  "--color-sidebar-primary": "var(--primary-700)",
  "--color-sidebar-foreground": "var(--primary-900)",
  "--color-sidebar": "var(--primary-100)",
  "--color-chart-5": "var(--primary-950)",
  "--color-chart-4": "var(--primary-700)",
  "--color-chart-3": "var(--primary-500)",
  "--color-chart-2": "var(--primary-300)",
  "--color-chart-1": "var(--primary-100)",
  "--color-ring": "var(--primary-400)",
  "--color-input": "var(--primary-100)",
  "--color-border": "var(--gray-100)",
  "--color-destructive": "var(--primary-800)",
  "--color-accent-foreground": "var(--primary-50)",
  "--color-accent": "var(--primary-500)",
  "--color-muted-foreground": "var(--primary-700)",
  "--color-muted": "var(--primary-100)",
  "--color-popover-foreground": "var(--primary-900)",
  "--color-popover": "var(--primary-100)",
  "--color-card-foreground": "var(--primary-900)",
  "--color-card": "var(--primary-50)",
  "--color-destructive-foreground": "var(--primary-50)",
  "--color-shadow-color": "oklch(0 0 0)",

  // Radius
  "--radius-sm": "4px",
  "--radius-md": "6px",
  "--radius-lg": "8px",
  "--radius-xl": "12px",
  "--radius-2xl": "16px",

  // Shadows
  "--shadow-xs": "0 1px 4px 0px hsl(0 0% 0% / 0.04)",
  "--shadow-sm": "0 4px 12px -4px hsl(0 0% 0% / 0.08)",
  "--shadow-md": "0 4px 6px -1px hsl(0 0% 0% / 0.1)",
  "--shadow-lg": "0 10px 15px -3px hsl(0 0% 0% / 0.1)",
  "--shadow-xl": "0 16px 20px -5px hsl(0 0% 0% / 0.1)",
  "--shadow-2xl": "0 20px 25px -5px hsl(0 0% 0% / 0.1)",
  "--shadow-3xl": "0 25px 50px -12px hsl(0 0% 0% / 0.12)",

  // Blur
  "--blur-sm": "2px",
  "--blur-md": "4px",
  "--blur-lg": "7px",
  "--blur-xl": "9px",
};

export { commonCSS, commonThemeVars };
