import { commonColors } from "./common/colors";

export const gameDevTheme = {
  theme: {
    "radius-sm": "0.25rem",
    "radius-md": "0.375rem",
    "radius-lg": "0.5rem",
    "radius-xl": "0.75rem",
    "radius-2xl": "1rem",
  },
  light: {
    ...commonColors,
    background: commonColors["yellow-50"],
    foreground: commonColors["gray-800"],
    primary: commonColors["pink-900"],
    "primary-foreground": commonColors["neutral-white"],
    secondary: commonColors["yellow-200"],
    "secondary-foreground": commonColors["gray-blue-950"],
    accent: commonColors["gray-blue-950"],
    "accent-foreground": commonColors["cyan-200"],
    card: commonColors["yellow-100"],
    "card-foreground": commonColors["gray-500"],
    muted: commonColors["cyan-100"],
    "muted-foreground": commonColors["gray-400"],
    success: commonColors["green-300"],
    "success-foreground": commonColors["green-50"],
    warning: commonColors["orange-400"],
    "warning-foreground": commonColors["orange-50"],
    destructive: commonColors["red-100"],
    "destructive-foreground": commonColors["neutral-white"],
    border: commonColors["pink-900"],
    input: commonColors["pink-50"],
    ring: commonColors["pink-800"],
    "chart-1": commonColors["pink-800"],
    "chart-2": commonColors["cyan-300"],
    "chart-3": commonColors["yellow-100"],
    "chart-4": commonColors["pink-400"],
    "chart-5": commonColors["pink-950"],
    sidebar: commonColors["yellow-50"],
    "sidebar-foreground": commonColors["gray-blue-950"],
    "sidebar-primary": commonColors["pink-900"],
    "sidebar-primary-foreground": commonColors["neutral-white"],
    "sidebar-accent": commonColors["pink-300"],
    "sidebar-accent-foreground": commonColors["gray-blue-950"],
    "sidebar-border": commonColors["pink-900"],
    "sidebar-ring": commonColors["pink-800"],
  },
  dark: {
    background: commonColors["gray-blue-900"],
    foreground: commonColors["pink-100"],
    primary: commonColors["yellow-100"],
    "primary-foreground": commonColors["gray-blue-900"],
    secondary: commonColors["pink-500"],
    "secondary-foreground": commonColors["gray-blue-900"],
    accent: commonColors["pink-700"],
    "accent-foreground": commonColors["pink-100"],
    card: commonColors["blue-primary-900"],
    "card-foreground": commonColors["pink-100"],
    muted: commonColors["gray-blue-500"],
    "muted-foreground": commonColors["pink-500"],
    success: commonColors["green-300"],
    "success-foreground": commonColors["green-50"],
    warning: commonColors["orange-400"],
    "warning-foreground": commonColors["orange-50"],
    destructive: commonColors["red-100"],
    "destructive-foreground": commonColors["neutral-white"],
    border: commonColors["cyan-900"],
    input: commonColors["cyan-950"],
    ring: commonColors["cyan-400"],
    "chart-1": commonColors["cyan-400"],
    "chart-2": commonColors["pink-500"],
    "chart-3": commonColors["pink-600"],
    "chart-4": commonColors["cyan-800"],
    "chart-5": commonColors["gray-blue-600"],
    sidebar: commonColors["gray-blue-900"],
    "sidebar-foreground": commonColors["pink-100"],
    "sidebar-primary": commonColors["yellow-100"],
    "sidebar-primary-foreground": commonColors["gray-blue-900"],
    "sidebar-accent": commonColors["pink-700"],
    "sidebar-accent-foreground": commonColors["pink-100"],
    "sidebar-border": commonColors["cyan-900"],
    "sidebar-ring": commonColors["cyan-400"],
  },
};
