import { commonColors } from "./common/colors";

export const gameDevTheme = {
  theme: {
    "radius-sm": "0.25rem",
    "radius-md": "0.375rem",
    "radius-lg": "0.5rem",
    "radius-xl": "0.75rem",
    "radius-2xl": "1rem",
  },
  light: {
    ...commonColors.light,
    background: commonColors.light["yellow-50"],
    foreground: commonColors.light["gray-850"],
    primary: commonColors.light["pink-400"],
    "primary-foreground": commonColors.light["white"],
    secondary: commonColors.light["yellow-300"],
    "secondary-foreground": commonColors.light["gray-900"],
    accent: commonColors.light["gray-900"],
    "accent-foreground": commonColors.light["accent-blue-100"],
    card: commonColors.light["yellow-200"],
    "card-foreground": commonColors.light["gray-600"],
    muted: commonColors.light["cyan-50"],
    "muted-foreground": commonColors.light["gray-700"],
    success: commonColors.light["green-300"],
    "success-foreground": commonColors.light["green-50"],
    warning: commonColors.light["accent-orange-100"],
    "warning-foreground": commonColors.light["accent-orange-50"],
    destructive: commonColors.light["red-100"],
    "destructive-foreground": commonColors.light["white"],
    border: commonColors.light["pink-400"],
    input: commonColors.light["pink-50"],
    ring: commonColors.light["pink-300"],
    "chart-1": commonColors.light["pink-300"],
    "chart-2": commonColors.light["cyan-200"],
    "chart-3": commonColors.light["yellow-200"],
    "chart-4": commonColors.light["pink-200"],
    "chart-5": commonColors.light["pink-500"],
    sidebar: commonColors.light["yellow-50"],
    "sidebar-foreground": commonColors.light["gray-900"],
    "sidebar-primary": commonColors.light["pink-400"],
    "sidebar-primary-foreground": commonColors.light["white"],
    "sidebar-accent": commonColors.light["pink-100"],
    "sidebar-accent-foreground": commonColors.light["gray-900"],
    "sidebar-border": commonColors.light["pink-400"],
    "sidebar-ring": commonColors.light["pink-300"],
  },
  dark: {
    ...commonColors.dark,
    background: commonColors.dark["yellow-50"],
    foreground: commonColors.dark["gray-850"],
    primary: commonColors.dark["pink-400"],
    "primary-foreground": commonColors.dark["white"],
    secondary: commonColors.dark["yellow-300"],
    "secondary-foreground": commonColors.dark["gray-900"],
    accent: commonColors.dark["gray-900"],
    "accent-foreground": commonColors.dark["accent-blue-100"],
    card: commonColors.dark["yellow-200"],
    "card-foreground": commonColors.dark["gray-600"],
    muted: commonColors.dark["cyan-50"],
    "muted-foreground": commonColors.dark["gray-700"],
    success: commonColors.dark["green-300"],
    "success-foreground": commonColors.dark["green-50"],
    warning: commonColors.dark["accent-orange-100"],
    "warning-foreground": commonColors.dark["accent-orange-50"],
    destructive: commonColors.dark["red-100"],
    "destructive-foreground": commonColors.dark["white"],
    border: commonColors.dark["pink-400"],
    input: commonColors.dark["pink-50"],
    ring: commonColors.dark["pink-300"],
    "chart-1": commonColors.dark["pink-300"],
    "chart-2": commonColors.dark["cyan-200"],
    "chart-3": commonColors.dark["yellow-200"],
    "chart-4": commonColors.dark["pink-200"],
    "chart-5": commonColors.dark["pink-500"],
    sidebar: commonColors.dark["yellow-50"],
    "sidebar-foreground": commonColors.dark["gray-900"],
    "sidebar-primary": commonColors.dark["pink-400"],
    "sidebar-primary-foreground": commonColors.dark["white"],
    "sidebar-accent": commonColors.dark["pink-100"],
    "sidebar-accent-foreground": commonColors.dark["gray-900"],
    "sidebar-border": commonColors.dark["pink-400"],
    "sidebar-ring": commonColors.dark["pink-300"],
  },
};
