import { commonColors } from "./common/colors";

export const gameDevTheme = {
  theme: {
    "radius-sm": "0.25rem",
    "radius-md": "0.375rem",
    "radius-lg": "0.5rem",
    "radius-xl": "0.75rem",
    "radius-2xl": "1rem",
  },
  light: {
    ...commonColors.light,
    background: commonColors.light["yellow-50"],
    foreground: commonColors.light["gray-800"],
    primary: commonColors.light["pink-900"],
    "primary-foreground": commonColors.light["neutral-white"],
    secondary: commonColors.light["yellow-200"],
    "secondary-foreground": commonColors.light["gray-blue-950"],
    accent: commonColors.light["gray-blue-950"],
    "accent-foreground": commonColors.light["cyan-200"],
    card: commonColors.light["yellow-100"],
    "card-foreground": commonColors.light["gray-500"],
    muted: commonColors.light["cyan-100"],
    "muted-foreground": commonColors.light["gray-400"],
    success: commonColors.light["green-300"],
    "success-foreground": commonColors.light["green-50"],
    warning: commonColors.light["orange-400"],
    "warning-foreground": commonColors.light["orange-50"],
    destructive: commonColors.light["red-100"],
    "destructive-foreground": commonColors.light["neutral-white"],
    border: commonColors.light["pink-900"],
    input: commonColors.light["pink-50"],
    ring: commonColors.light["pink-800"],
    "chart-1": commonColors.light["pink-800"],
    "chart-2": commonColors.light["cyan-300"],
    "chart-3": commonColors.light["yellow-100"],
    "chart-4": commonColors.light["pink-400"],
    "chart-5": commonColors.light["pink-950"],
    sidebar: commonColors.light["yellow-50"],
    "sidebar-foreground": commonColors.light["gray-blue-950"],
    "sidebar-primary": commonColors.light["pink-900"],
    "sidebar-primary-foreground": commonColors.light["neutral-white"],
    "sidebar-accent": commonColors.light["pink-300"],
    "sidebar-accent-foreground": commonColors.light["gray-blue-950"],
    "sidebar-border": commonColors.light["pink-900"],
    "sidebar-ring": commonColors.light["pink-800"],
  },
  dark: {
    ...commonColors.dark,
    background: commonColors.dark["gray-blue-900"],
    foreground: commonColors.dark["pink-100"],
    primary: commonColors.dark["yellow-100"],
    "primary-foreground": commonColors.dark["gray-blue-900"],
    secondary: commonColors.dark["pink-500"],
    "secondary-foreground": commonColors.dark["gray-blue-900"],
    accent: commonColors.dark["pink-700"],
    "accent-foreground": commonColors.dark["pink-100"],
    card: commonColors.dark["blue-primary-900"],
    "card-foreground": commonColors.dark["pink-100"],
    muted: commonColors.dark["gray-blue-500"],
    "muted-foreground": commonColors.dark["pink-500"],
    success: commonColors.dark["green-300"],
    "success-foreground": commonColors.dark["green-50"],
    warning: commonColors.dark["orange-400"],
    "warning-foreground": commonColors.dark["orange-50"],
    destructive: commonColors.dark["red-100"],
    "destructive-foreground": commonColors.dark["neutral-white"],
    border: commonColors.dark["cyan-900"],
    input: commonColors.dark["cyan-950"],
    ring: commonColors.dark["cyan-400"],
    "chart-1": commonColors.dark["cyan-400"],
    "chart-2": commonColors.dark["pink-500"],
    "chart-3": commonColors.dark["pink-600"],
    "chart-4": commonColors.dark["cyan-800"],
    "chart-5": commonColors.dark["gray-blue-600"],
    sidebar: commonColors.dark["gray-blue-900"],
    "sidebar-foreground": commonColors.dark["pink-100"],
    "sidebar-primary": commonColors.dark["yellow-100"],
    "sidebar-primary-foreground": commonColors.dark["gray-blue-900"],
    "sidebar-accent": commonColors.dark["pink-700"],
    "sidebar-accent-foreground": commonColors.dark["pink-100"],
    "sidebar-border": commonColors.dark["cyan-900"],
    "sidebar-ring": commonColors.dark["cyan-400"],
  },
};
