import { commonColors } from "./common/colors";

export const itTheme = {
  theme: {
    "radius-sm": "0.25rem",
    "radius-md": "0.375rem",
    "radius-lg": "0.5rem",
    "radius-xl": "0.75rem",
    "radius-2xl": "0.75rem",
  },
  light: {
    ...commonColors.light,
    background: commonColors.light["neutral-white"],
    foreground: commonColors.light["gray-blue-300"],
    primary: commonColors.light["flashy-green-300"],
    "primary-foreground": commonColors.light["neutral-white"],
    secondary: "#e0f2fe",
    "secondary-foreground": commonColors.light["gray-blue-200"],
    accent: commonColors.light["flashy-green-200"],
    "accent-foreground": commonColors.light["gray-blue-300"],
    card: commonColors.light["neutral-white"],
    "card-foreground": commonColors.light["gray-blue-300"],
    muted: commonColors.light["baby-blue-50"],
    "muted-foreground": commonColors.light["gray-blue-100"],
    success: commonColors.light["green-300"],
    "success-foreground": commonColors.light["green-50"],
    warning: commonColors.light["orange-400"],
    "warning-foreground": commonColors.light["orange-50"],
    destructive: commonColors.light["red-200"],
    "destructive-foreground": commonColors.light["neutral-white"],
    border: "#e5e7eb",
    input: commonColors.light["neutral-white"],
    ring: commonColors.light["flashy-green-300"],
    "chart-1": commonColors.light["baby-blue-100"],
    "chart-2": commonColors.light["baby-blue-200"],
    "chart-3": commonColors.light["baby-blue-400"],
    "chart-4": commonColors.light["baby-blue-500"],
    "chart-5": commonColors.light["baby-blue-600"],
    sidebar: commonColors.light["neutral-white"],
    "sidebar-foreground": commonColors.light["gray-blue-300"],
    "sidebar-primary": commonColors.light["flashy-green-300"],
    "sidebar-primary-foreground": commonColors.light["neutral-white"],
    "sidebar-accent": commonColors.light["flashy-green-200"],
    "sidebar-accent-foreground": commonColors.light["gray-blue-300"],
    "sidebar-border": "#e5e7eb",
    "sidebar-ring": commonColors.light["flashy-green-300"],
  },
  dark: {
    ...commonColors.dark,
    background: commonColors.dark["blue-primary-800"],
    foreground: commonColors.dark["gray-50"],
    primary: commonColors.dark["flashy-green-300"],
    "primary-foreground": commonColors.dark["blue-primary-800"],
    secondary: commonColors.dark["gray-blue-400"],
    "secondary-foreground": commonColors.dark["gray-200"],
    accent: commonColors.dark["gray-blue-300"],
    "accent-foreground": commonColors.dark["gray-200"],
    card: commonColors.dark["gray-blue-800"],
    "card-foreground": commonColors.dark["gray-50"],
    muted: commonColors.dark["gray-blue-700"],
    "muted-foreground": commonColors.dark["gray-blue-100"],
    success: commonColors.dark["green-300"],
    "success-foreground": commonColors.dark["green-50"],
    warning: commonColors.dark["orange-400"],
    "warning-foreground": commonColors.dark["orange-50"],
    destructive: commonColors.dark["red-200"],
    "destructive-foreground": commonColors.dark["neutral-white"],
    border: commonColors.dark["gray-blue-200"],
    input: commonColors.dark["gray-blue-200"],
    ring: commonColors.dark["flashy-green-300"],
    "chart-1": commonColors.dark["baby-blue-100"],
    "chart-2": commonColors.dark["baby-blue-200"],
    "chart-3": commonColors.dark["baby-blue-400"],
    "chart-4": commonColors.dark["baby-blue-500"],
    "chart-5": commonColors.dark["baby-blue-600"],
    sidebar: commonColors.dark["baby-blue-50"],
    "sidebar-foreground": commonColors.dark["blue-primary-950"],
    "sidebar-primary": commonColors.dark["flashy-green-300"],
    "sidebar-primary-foreground": commonColors.dark["blue-primary-800"],
    "sidebar-accent": commonColors.dark["baby-blue-50"],
    "sidebar-accent-foreground": commonColors.dark["gray-blue-700"],
    "sidebar-border": commonColors.dark["gray-blue-200"],
    "sidebar-ring": commonColors.dark["flashy-green-300"],
  },
};
