import { commonColors } from "./common/colors";

export const itTheme = {
  theme: {
    "radius-sm": "0.25rem",
    "radius-md": "0.375rem",
    "radius-lg": "0.5rem",
    "radius-xl": "0.75rem",
    "radius-2xl": "0.75rem",
  },
  light: {
    ...commonColors.light,
    background: commonColors.light["white"],
    foreground: commonColors.light["gray-950"],
    primary: commonColors.light["green-400"],
    "primary-foreground": commonColors.light["white"],
    secondary: commonColors.light["green-400"],
    "secondary-foreground": commonColors.light["white"],
    accent: commonColors.light["gray-100"],
    "accent-foreground": commonColors.light["gray-900"],
    card: commonColors.light["white"],
    "card-foreground": commonColors.light["gray-950"],
    muted: commonColors.light["gray-100"],
    "muted-foreground": commonColors.light["gray-600"],
    success: commonColors.light["green-300"],
    "success-foreground": commonColors.light["green-50"],
    warning: commonColors.light["accent-orange-100"],
    "warning-foreground": commonColors.light["accent-orange-50"],
    destructive: commonColors.light["red-200"],
    "destructive-foreground": commonColors.light["white"],
    border: commonColors.light["gray-200"],
    input: commonColors.light["gray-200"],
    ring: commonColors.light["gray-400"],
    "chart-1": commonColors.light["baby-blue-50"],
    "chart-2": commonColors.light["baby-blue-100"],
    "chart-3": commonColors.light["baby-blue-200"],
    "chart-4": commonColors.light["baby-blue-300"],
    "chart-5": commonColors.light["baby-blue-400"],
    sidebar: commonColors.light["gray-100"],
    "sidebar-foreground": commonColors.light["gray-950"],
    "sidebar-primary": commonColors.light["green-400"],
    "sidebar-primary-foreground": commonColors.light["white"],
    "sidebar-accent": commonColors.light["gray-100"],
    "sidebar-accent-foreground": commonColors.light["gray-900"],
    "sidebar-border": commonColors.light["gray-200"],
    "sidebar-ring": commonColors.light["gray-400"],
  },
  dark: {
    ...commonColors.dark,
    background: commonColors.dark["white"],
    foreground: commonColors.dark["gray-950"],
    primary: commonColors.dark["green-400"],
    "primary-foreground": commonColors.dark["white"],
    secondary: commonColors.dark["green-400"],
    "secondary-foreground": commonColors.dark["white"],
    accent: commonColors.dark["gray-100"],
    "accent-foreground": commonColors.dark["gray-900"],
    card: commonColors.dark["white"],
    "card-foreground": commonColors.dark["gray-950"],
    muted: commonColors.dark["gray-100"],
    "muted-foreground": commonColors.dark["gray-600"],
    success: commonColors.dark["green-300"],
    "success-foreground": commonColors.dark["green-50"],
    warning: commonColors.dark["accent-orange-100"],
    "warning-foreground": commonColors.dark["accent-orange-50"],
    destructive: commonColors.dark["red-200"],
    "destructive-foreground": commonColors.dark["white"],
    border: commonColors.dark["gray-200"],
    input: commonColors.dark["gray-200"],
    ring: commonColors.dark["gray-400"],
    "chart-1": commonColors.dark["baby-blue-50"],
    "chart-2": commonColors.dark["baby-blue-100"],
    "chart-3": commonColors.dark["baby-blue-200"],
    "chart-4": commonColors.dark["baby-blue-300"],
    "chart-5": commonColors.dark["baby-blue-400"],
    sidebar: commonColors.dark["gray-100"],
    "sidebar-foreground": commonColors.dark["gray-950"],
    "sidebar-primary": commonColors.dark["green-400"],
    "sidebar-primary-foreground": commonColors.dark["white"],
    "sidebar-accent": commonColors.dark["gray-100"],
    "sidebar-accent-foreground": commonColors.dark["gray-900"],
    "sidebar-border": commonColors.dark["gray-200"],
    "sidebar-ring": commonColors.dark["gray-400"],
  },
};
