import { commonColors } from "./common/colors";

export const primaryTheme = {
  theme: {
    "radius-sm": "0.25rem",
    "radius-md": "0.375rem",
    "radius-lg": "0.5rem",
    "radius-xl": "0.75rem",
    "radius-2xl": "0.75rem",
  },
  light: {
    ...commonColors,
    background: commonColors["neutral-white"],
    foreground: commonColors["baby-blue-1000"],
    primary: commonColors["baby-blue-800"],
    "primary-foreground": commonColors["neutral-white"],
    secondary: commonColors["blue-primary-200"],
    "secondary-foreground": commonColors["baby-blue-900"],
    accent: commonColors["cyan-50"],
    "accent-foreground": commonColors["cyan-700"],
    card: commonColors["neutral-white"],
    "card-foreground": commonColors["blue-primary-500"],
    muted: commonColors["blue-primary-100"],
    "muted-foreground": commonColors["blue-primary-400"],
    success: commonColors["green-300"],
    "success-foreground": commonColors["green-50"],
    warning: commonColors["orange-400"],
    "warning-foreground": commonColors["orange-50"],
    destructive: commonColors["red-200"],
    "destructive-foreground": commonColors["red-50"],
    border: commonColors["blue-primary-200"],
    input: commonColors["blue-primary-100"],
    ring: commonColors["blue-primary-300"],
    "chart-1": commonColors["baby-blue-100"],
    "chart-2": commonColors["baby-blue-200"],
    "chart-3": commonColors["baby-blue-400"],
    "chart-4": commonColors["baby-blue-500"],
    "chart-5": commonColors["baby-blue-600"],
    sidebar: commonColors["blue-primary-100"],
    "sidebar-foreground": commonColors["blue-primary-500"],
    "sidebar-primary": commonColors["baby-blue-800"],
    "sidebar-primary-foreground": commonColors["neutral-white"],
    "sidebar-accent": commonColors["blue-primary-200"],
    "sidebar-accent-foreground": commonColors["blue-primary-500"],
    "sidebar-border": commonColors["blue-primary-200"],
    "sidebar-ring": commonColors["blue-primary-300"],
  },
  dark: {
    background: commonColors["gray-blue-1000"],
    foreground: commonColors["blue-primary-50"],
    primary: commonColors["blue-primary-300"],
    "primary-foreground": commonColors["baby-blue-1000"],
    secondary: commonColors["gray-900"],
    "secondary-foreground": commonColors["blue-primary-50"],
    accent: commonColors["gray-blue-1000"],
    "accent-foreground": commonColors["blue-primary-50"],
    card: commonColors["gray-950"],
    "card-foreground": commonColors["blue-primary-50"],
    muted: commonColors["gray-900"],
    "muted-foreground": commonColors["gray-200"],
    success: commonColors["green-300"],
    "success-foreground": commonColors["green-50"],
    warning: commonColors["orange-400"],
    "warning-foreground": commonColors["orange-50"],
    destructive: commonColors["red-200"],
    "destructive-foreground": commonColors["red-50"],
    border: commonColors["gray-900"],
    input: commonColors["gray-700"],
    ring: commonColors["blue-primary-300"],
    "chart-1": commonColors["baby-blue-100"],
    "chart-2": commonColors["baby-blue-200"],
    "chart-3": commonColors["baby-blue-400"],
    "chart-4": commonColors["baby-blue-500"],
    "chart-5": commonColors["baby-blue-600"],
    sidebar: commonColors["gray-950"],
    "sidebar-foreground": commonColors["blue-primary-50"],
    "sidebar-primary": commonColors["blue-primary-300"],
    "sidebar-primary-foreground": commonColors["baby-blue-1000"],
    "sidebar-accent": commonColors["baby-blue-1000"],
    "sidebar-accent-foreground": commonColors["blue-primary-50"],
    "sidebar-border": commonColors["gray-900"],
    "sidebar-ring": commonColors["blue-primary-300"],
  },
};
