import { commonColors } from "./common/colors";

export const roboticsTheme = {
  theme: {
    "radius-sm": "0.125rem",
    "radius-md": "0.125rem",
    "radius-lg": "0.25rem",
    "radius-xl": "0.25rem",
    "radius-2xl": "0.25rem",
  },
  light: {
    ...commonColors,
    background: commonColors["neutral-white"],
    foreground: commonColors["neutral-black"],
    primary: commonColors["baby-blue-700"],
    "primary-foreground": commonColors["neutral-white"],
    secondary: commonColors["baby-blue-800"],
    "secondary-foreground": commonColors["neutral-white"],
    accent: commonColors["cyan-500"],
    "accent-foreground": commonColors["blue-primary-700"],
    card: commonColors["neutral-white"],
    "card-foreground": commonColors["neutral-black"],
    muted: commonColors["gray-blue-50"],
    "muted-foreground": commonColors["gray-600"],
    success: commonColors["green-300"],
    "success-foreground": commonColors["green-50"],
    warning: commonColors["orange-400"],
    "warning-foreground": commonColors["orange-50"],
    destructive: commonColors["red-200"],
    "destructive-foreground": commonColors["neutral-white"],
    border: commonColors["neutral-black"],
    input: commonColors["neutral-white"],
    ring: commonColors["cyan-500"],
    "chart-1": commonColors["accent-red-50"],
    "chart-2": commonColors["accent-flash-50"],
    "chart-3": commonColors["accent-blue-50"],
    "chart-4": commonColors["accent-green-50"],
    "chart-5": commonColors["accent-magenta-50"],
    sidebar: commonColors["gray-blue-50"],
    "sidebar-foreground": commonColors["neutral-black"],
    "sidebar-primary": commonColors["baby-blue-700"],
    "sidebar-primary-foreground": commonColors["neutral-white"],
    "sidebar-accent": commonColors["cyan-500"],
    "sidebar-accent-foreground": commonColors["blue-primary-700"],
    "sidebar-border": commonColors["neutral-black"],
    "sidebar-ring": commonColors["cyan-500"],
  },
  dark: {
    background: commonColors["neutral-black"],
    foreground: commonColors["neutral-white"],
    primary: commonColors["baby-blue-400"],
    "primary-foreground": commonColors["neutral-white"],
    secondary: commonColors["baby-blue-700"],
    "secondary-foreground": commonColors["neutral-white"],
    accent: commonColors["cyan-600"],
    "accent-foreground": commonColors["neutral-white"],
    card: commonColors["gray-900"],
    "card-foreground": commonColors["neutral-white"],
    muted: commonColors["gray-1000"],
    "muted-foreground": commonColors["gray-100"],
    success: commonColors["green-300"],
    "success-foreground": commonColors["green-50"],
    warning: commonColors["orange-400"],
    "warning-foreground": commonColors["orange-50"],
    destructive: commonColors["red-200"],
    "destructive-foreground": commonColors["neutral-white"],
    border: commonColors["gray-300"],
    input: commonColors["gray-300"],
    ring: commonColors["cyan-600"],
    "chart-1": commonColors["accent-red-50"],
    "chart-2": commonColors["accent-flash-50"],
    "chart-3": commonColors["accent-blue-50"],
    "chart-4": commonColors["accent-green-50"],
    "chart-5": commonColors["accent-magenta-50"],
    sidebar: commonColors["neutral-black"],
    "sidebar-foreground": commonColors["neutral-white"],
    "sidebar-primary": commonColors["baby-blue-400"],
    "sidebar-primary-foreground": commonColors["neutral-white"],
    "sidebar-accent": commonColors["cyan-600"],
    "sidebar-accent-foreground": commonColors["neutral-white"],
    "sidebar-border": commonColors["gray-300"],
    "sidebar-ring": commonColors["cyan-600"],
  },
};
