import { commonColors } from "./common/colors";

export const roboticsTheme = {
  light: {
    ...commonColors.light,
    background: commonColors.light["white"],
    foreground: commonColors.light["blue-primary-950"],
    primary: commonColors.light["blue-primary-500"],
    "primary-foreground": commonColors.light["white"],
    secondary: commonColors.light["blue-primary-600"],
    "secondary-foreground": commonColors.light["white"],
    accent: commonColors.light["accent-blue-200"],
    "accent-foreground": commonColors.light["blue-primary-950"],
    card: commonColors.light["white"],
    "card-foreground": commonColors.light["blue-primary-800"],
    muted: commonColors.light["blue-primary-100"],
    "muted-foreground": commonColors.light["blue-primary-300"],
    success: commonColors.light["green-300"],
    "success-foreground": commonColors.light["green-50"],
    warning: commonColors.light["accent-orange-100"],
    "warning-foreground": commonColors.light["accent-orange-50"],
    destructive: commonColors.light["red-100"],
    "destructive-foreground": commonColors.light["white"],
    border: commonColors.light["gray-850"],
    input: commonColors.light["blue-primary-100"],
    ring: commonColors.light["blue-primary-500"],
    "chart-1": commonColors.light["blue-primary-400"],
    "chart-2": commonColors.light["accent-blue-200"],
    "chart-3": commonColors.light["blue-primary-500"],
    "chart-4": commonColors.light["blue-primary-600"],
    "chart-5": commonColors.light["blue-primary-950"],
    sidebar: commonColors.light["blue-primary-300"],
    "sidebar-foreground": commonColors.light["blue-primary-950"],
    "sidebar-primary": commonColors.light["blue-primary-500"],
    "sidebar-primary-foreground": commonColors.light["white"],
    "sidebar-accent": commonColors.light["blue-primary-400"],
    "sidebar-accent-foreground": commonColors.light["white"],
    "sidebar-border": commonColors.light["gray-850"],
    "sidebar-ring": commonColors.light["blue-primary-500"],
  },
  dark: {
    ...commonColors.dark,
    background: commonColors.dark["white"],
    foreground: commonColors.dark["blue-primary-950"],
    primary: commonColors.dark["blue-primary-500"],
    "primary-foreground": commonColors.dark["white"],
    secondary: commonColors.dark["blue-primary-600"],
    "secondary-foreground": commonColors.dark["white"],
    accent: commonColors.dark["accent-blue-200"],
    "accent-foreground": commonColors.dark["blue-primary-950"],
    card: commonColors.dark["white"],
    "card-foreground": commonColors.dark["blue-primary-800"],
    muted: commonColors.dark["blue-primary-100"],
    "muted-foreground": commonColors.dark["blue-primary-300"],
    success: commonColors.dark["green-300"],
    "success-foreground": commonColors.dark["green-50"],
    warning: commonColors.dark["accent-orange-100"],
    "warning-foreground": commonColors.dark["accent-orange-50"],
    destructive: commonColors.dark["red-100"],
    "destructive-foreground": commonColors.dark["white"],
    border: commonColors.dark["gray-850"],
    input: commonColors.dark["blue-primary-100"],
    ring: commonColors.dark["blue-primary-500"],
    "chart-1": commonColors.dark["blue-primary-400"],
    "chart-2": commonColors.dark["accent-blue-200"],
    "chart-3": commonColors.dark["blue-primary-500"],
    "chart-4": commonColors.dark["blue-primary-600"],
    "chart-5": commonColors.dark["blue-primary-950"],
    sidebar: commonColors.dark["blue-primary-300"],
    "sidebar-foreground": commonColors.dark["blue-primary-950"],
    "sidebar-primary": commonColors.dark["blue-primary-500"],
    "sidebar-primary-foreground": commonColors.dark["white"],
    "sidebar-accent": commonColors.dark["blue-primary-400"],
    "sidebar-accent-foreground": commonColors.dark["white"],
    "sidebar-border": commonColors.dark["gray-850"],
    "sidebar-ring": commonColors.dark["blue-primary-500"],
  },
};
