import { commonColors } from "./common/colors";

export const secondaryTheme = {
  theme: {
    "radius-sm": "0.25rem",
    "radius-md": "0.375rem",
    "radius-lg": "0.5rem",
    "radius-xl": "0.75rem",
    "radius-2xl": "0.75rem",
  },
  light: {
    ...commonColors.light,
    background: commonColors.light["neutral-white"],
    foreground: commonColors.light["purple-secondary-900"],
    primary: commonColors.light["purple-secondary-600"],
    "primary-foreground": commonColors.light["neutral-white"],
    secondary: commonColors.light["purple-secondary-200"],
    "secondary-foreground": commonColors.light["purple-secondary-700"],
    accent: commonColors.light["orange-50"],
    "accent-foreground": commonColors.light["orange-400"],
    card: commonColors.light["neutral-white"],
    "card-foreground": commonColors.light["purple-secondary-800"],
    muted: commonColors.light["purple-secondary-50"],
    "muted-foreground": commonColors.light["purple-secondary-300"],
    success: commonColors.light["green-300"],
    "success-foreground": commonColors.light["green-50"],
    warning: commonColors.light["orange-400"],
    "warning-foreground": commonColors.light["orange-50"],
    destructive: commonColors.light["red-200"],
    "destructive-foreground": commonColors.light["red-50"],
    border: commonColors.light["purple-secondary-100"],
    input: commonColors.light["purple-secondary-50"],
    ring: commonColors.light["pink-200"],
    "chart-1": commonColors.light["orange-100"],
    "chart-2": commonColors.light["orange-200"],
    "chart-3": commonColors.light["orange-400"],
    "chart-4": commonColors.light["orange-300"],
    "chart-5": commonColors.light["orange-500"],
    sidebar: commonColors.light["purple-secondary-50"],
    "sidebar-foreground": commonColors.light["purple-secondary-800"],
    "sidebar-primary": commonColors.light["purple-secondary-600"],
    "sidebar-primary-foreground": commonColors.light["neutral-white"],
    "sidebar-accent": commonColors.light["purple-secondary-200"],
    "sidebar-accent-foreground": commonColors.light["purple-secondary-800"],
    "sidebar-border": commonColors.light["purple-secondary-100"],
    "sidebar-ring": commonColors.light["pink-200"],
  },
  dark: {
    ...commonColors.dark,
    background: commonColors.dark["blue-primary-800"],
    foreground: commonColors.dark["blue-primary-200"],
    primary: commonColors.dark["purple-secondary-400"],
    "primary-foreground": commonColors.dark["neutral-white"],
    secondary: commonColors.dark["blue-primary-500"],
    "secondary-foreground": commonColors.dark["blue-primary-200"],
    accent: commonColors.dark["orange-600"],
    "accent-foreground": commonColors.dark["orange-50"],
    card: commonColors.dark["blue-primary-500"],
    "card-foreground": commonColors.dark["blue-primary-200"],
    muted: commonColors.dark["blue-primary-600"],
    "muted-foreground": commonColors.dark["purple-secondary-300"],
    success: commonColors.dark["green-300"],
    "success-foreground": commonColors.dark["green-50"],
    warning: commonColors.dark["orange-400"],
    "warning-foreground": commonColors.dark["orange-50"],
    destructive: commonColors.dark["red-200"],
    "destructive-foreground": commonColors.dark["red-50"],
    border: commonColors.dark["purple-secondary-500"],
    input: commonColors.dark["purple-secondary-950"],
    ring: commonColors.dark["purple-secondary-400"],
    "chart-1": commonColors.dark["orange-100"],
    "chart-2": commonColors.dark["orange-200"],
    "chart-3": commonColors.dark["orange-400"],
    "chart-4": commonColors.dark["orange-300"],
    "chart-5": commonColors.dark["orange-500"],
    sidebar: commonColors.dark["blue-primary-800"],
    "sidebar-foreground": commonColors.dark["blue-primary-200"],
    "sidebar-primary": commonColors.dark["purple-secondary-400"],
    "sidebar-primary-foreground": commonColors.dark["neutral-white"],
    "sidebar-accent": commonColors.dark["orange-600"],
    "sidebar-accent-foreground": commonColors.dark["orange-50"],
    "sidebar-border": commonColors.dark["purple-secondary-500"],
    "sidebar-ring": commonColors.dark["purple-secondary-400"],
  },
};
