import { commonColors } from './common/colors';

export const itTheme = {
  theme: {
    'radius-sm': '0.25rem',
    'radius-md': '0.375rem',
    'radius-lg': '0.5rem',
    'radius-xl': '0.75rem',
    'radius-2xl': '0.75rem',
  },
  light: {
    ...commonColors,
    background: commonColors['neutral-white'],
    foreground: commonColors['gray-blue-300'],
    primary: commonColors['flashy-green-300'],
    'primary-foreground': commonColors['neutral-white'],
    secondary: '#e0f2fe',
    'secondary-foreground': commonColors['gray-blue-200'],
    accent: commonColors['flashy-green-200'],
    'accent-foreground': commonColors['gray-blue-300'],
    card: commonColors['neutral-white'],
    'card-foreground': commonColors['gray-blue-300'],
    muted: commonColors['baby-blue-50'],
    'muted-foreground': commonColors['gray-blue-100'],
    success: commonColors['green-300'],
    'success-foreground': commonColors['green-50'],
    warning: commonColors['orange-400'],
    'warning-foreground': commonColors['orange-50'],
    destructive: commonColors['red-200'],
    'destructive-foreground': commonColors['neutral-white'],
    border: '#e5e7eb',
    input: commonColors['neutral-white'],
    ring: commonColors['flashy-green-300'],
    'chart-1': commonColors['baby-blue-100'],
    'chart-2': commonColors['baby-blue-200'],
    'chart-3': commonColors['baby-blue-400'],
    'chart-4': commonColors['baby-blue-500'],
    'chart-5': commonColors['baby-blue-600'],
    sidebar: commonColors['neutral-white'],
    'sidebar-foreground': commonColors['gray-blue-300'],
    'sidebar-primary': commonColors['flashy-green-300'],
    'sidebar-primary-foreground': commonColors['neutral-white'],
    'sidebar-accent': commonColors['flashy-green-200'],
    'sidebar-accent-foreground': commonColors['gray-blue-300'],
    'sidebar-border': '#e5e7eb',
    'sidebar-ring': commonColors['flashy-green-300'],
  },
  dark: {
    background: commonColors['blue-primary-800'],
    foreground: commonColors['gray-50'],
    primary: commonColors['flashy-green-300'],
    'primary-foreground': commonColors['blue-primary-800'],
    secondary: commonColors['gray-blue-400'],
    'secondary-foreground': commonColors['gray-200'],
    accent: commonColors['gray-blue-300'],
    'accent-foreground': commonColors['gray-200'],
    card: commonColors['gray-blue-800'],
    'card-foreground': commonColors['gray-50'],
    muted: commonColors['gray-blue-700'],
    'muted-foreground': commonColors['gray-blue-100'],
    success: commonColors['green-300'],
    'success-foreground': commonColors['green-50'],
    warning: commonColors['orange-400'],
    'warning-foreground': commonColors['orange-50'],
    destructive: commonColors['red-200'],
    'destructive-foreground': commonColors['neutral-white'],
    border: commonColors['gray-blue-200'],
    input: commonColors['gray-blue-200'],
    ring: commonColors['flashy-green-300'],
    'chart-1': commonColors['baby-blue-100'],
    'chart-2': commonColors['baby-blue-200'],
    'chart-3': commonColors['baby-blue-400'],
    'chart-4': commonColors['baby-blue-500'],
    'chart-5': commonColors['baby-blue-600'],
    sidebar: commonColors['baby-blue-50'],
    'sidebar-foreground': commonColors['blue-primary-950'],
    'sidebar-primary': commonColors['flashy-green-300'],
    'sidebar-primary-foreground': commonColors['blue-primary-800'],
    'sidebar-accent': commonColors['baby-blue-50'],
    'sidebar-accent-foreground': commonColors['gray-blue-700'],
    'sidebar-border': commonColors['gray-blue-200'],
    'sidebar-ring': commonColors['flashy-green-300'],
  },
};
