import { commonColors } from './common/colors';

export const secondaryTheme = {
  theme: {
    'radius-sm': '0.25rem',
    'radius-md': '0.375rem',
    'radius-lg': '0.5rem',
    'radius-xl': '0.75rem',
    'radius-2xl': '0.75rem',
  },
  light: {
    ...commonColors,
    background: commonColors['neutral-white'],
    foreground: commonColors['purple-secondary-900'],
    primary: commonColors['purple-secondary-600'],
    'primary-foreground': commonColors['neutral-white'],
    secondary: commonColors['purple-secondary-200'],
    'secondary-foreground': commonColors['purple-secondary-700'],
    accent: commonColors['orange-50'],
    'accent-foreground': commonColors['orange-400'],
    card: commonColors['neutral-white'],
    'card-foreground': commonColors['purple-secondary-800'],
    muted: commonColors['purple-secondary-50'],
    'muted-foreground': commonColors['purple-secondary-300'],
    success: commonColors['green-300'],
    'success-foreground': commonColors['green-50'],
    warning: commonColors['orange-400'],
    'warning-foreground': commonColors['orange-50'],
    destructive: commonColors['red-200'],
    'destructive-foreground': commonColors['red-50'],
    border: commonColors['purple-secondary-100'],
    input: commonColors['purple-secondary-50'],
    ring: commonColors['pink-200'],
    'chart-1': commonColors['orange-100'],
    'chart-2': commonColors['orange-200'],
    'chart-3': commonColors['orange-400'],
    'chart-4': commonColors['orange-300'],
    'chart-5': commonColors['orange-500'],
    sidebar: commonColors['purple-secondary-50'],
    'sidebar-foreground': commonColors['purple-secondary-800'],
    'sidebar-primary': commonColors['purple-secondary-600'],
    'sidebar-primary-foreground': commonColors['neutral-white'],
    'sidebar-accent': commonColors['purple-secondary-200'],
    'sidebar-accent-foreground': commonColors['purple-secondary-800'],
    'sidebar-border': commonColors['purple-secondary-100'],
    'sidebar-ring': commonColors['pink-200'],
  },
  dark: {
    background: commonColors['blue-primary-800'],
    foreground: commonColors['blue-primary-200'],
    primary: commonColors['purple-secondary-400'],
    'primary-foreground': commonColors['neutral-white'],
    secondary: commonColors['blue-primary-500'],
    'secondary-foreground': commonColors['blue-primary-200'],
    accent: commonColors['orange-600'],
    'accent-foreground': commonColors['orange-50'],
    card: commonColors['blue-primary-500'],
    'card-foreground': commonColors['blue-primary-200'],
    muted: commonColors['blue-primary-600'],
    'muted-foreground': commonColors['purple-secondary-300'],
    success: commonColors['green-300'],
    'success-foreground': commonColors['green-50'],
    warning: commonColors['orange-400'],
    'warning-foreground': commonColors['orange-50'],
    destructive: commonColors['red-200'],
    'destructive-foreground': commonColors['red-50'],
    border: commonColors['purple-secondary-500'],
    input: commonColors['purple-secondary-950'],
    ring: commonColors['purple-secondary-400'],
    'chart-1': commonColors['orange-100'],
    'chart-2': commonColors['orange-200'],
    'chart-3': commonColors['orange-400'],
    'chart-4': commonColors['orange-300'],
    'chart-5': commonColors['orange-500'],
    sidebar: commonColors['blue-primary-800'],
    'sidebar-foreground': commonColors['blue-primary-200'],
    'sidebar-primary': commonColors['purple-secondary-400'],
    'sidebar-primary-foreground': commonColors['neutral-white'],
    'sidebar-accent': commonColors['orange-600'],
    'sidebar-accent-foreground': commonColors['orange-50'],
    'sidebar-border': commonColors['purple-secondary-500'],
    'sidebar-ring': commonColors['purple-secondary-400'],
  },
};
